config/routes.rb
Rails.application.routes.draw do
  resources :complains
  get 'admin_user/index'
  get 'admin_user/change_pass/:id', to: 'admin_user#change_pass', as: :admin_user_change_pass
  get 'admin_user/new'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "infos#index", as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :infos do
    get 'download_csv', :on => :collection
    #get "import"
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/print_pdf", to: "infos#print_pdf"

  patch '/admin_user/:id/update', to: 'admin_user#update', as: :update_admin_user
  #patch '/user/:id/update', to: 'admin_users#update', as: :update_admin_user
end

app/models/complain.rb
class Complain < ApplicationRecord
  Devise = ['monitor', 'keyboard', 'mouse']
end

app/controllers/complains_controller.rb
class ComplainsController < ApplicationController
  before_action :set_complain, only: [:show, :edit, :update, :destroy]

  # GET /complains
  # GET /complains.json
  def index
    @complains = Complain.all
    @not_all = Complain.where('user_id = ?', current_user.id)
  end

  # GET /complains/1
  # GET /complains/1.json
  def show
  end

  # GET /complains/new
  def new
    @complain = Complain.new
  end

  # GET /complains/1/edit
  def edit
  end

  # POST /complains
  # POST /complains.json
  def create
    @complain = Complain.new(complain_params)

    respond_to do |format|
      if @complain.save
        format.html { redirect_to @complain, notice: 'Complain was successfully created.' }
        format.json { render :show, status: :created, location: @complain }
      else
        format.html { render :new }
        format.json { render json: @complain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complains/1
  # PATCH/PUT /complains/1.json
  def update
    respond_to do |format|
      if @complain.update(complain_params)
        format.html { redirect_to @complain, notice: 'Complain was successfully updated.' }
        format.json { render :show, status: :ok, location: @complain }
      else
        format.html { render :edit }
        format.json { render json: @complain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complains/1
  # DELETE /complains/1.json
  def destroy
    @complain.destroy
    respond_to do |format|
      format.html { redirect_to complains_url, notice: 'Complain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complain
      @complain = Complain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complain_params
      params.require(:complain).permit(:name, :user_id, :devise, :complain)
    end
end

app/helpers/complains_helper.rb
module ComplainsHelper
end

app/views/complains/_form.html.erb
<div class="well col-md-4 col-md-offset-4">
<%= form_for(complain) do |f| %>
  <% if complain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complain.errors.count, "error") %> prohibited this complain from being saved:</h2>

      <ul>
      <% complain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if request.original_url.include? "complains/new" %>
    <h1 class="well">New Complain</h1>
  <% elsif request.original_url.include? "complains/#{params[:id]}/edit" %>
    <h1 class="well">Edit Complain</h1>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.number_field :user_id, :value => current_user.id, readonly: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :value => current_user.username, readonly: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :devise %>
    <%= f.select :devise, options_for_select(['Monitor','Keyboard','Mouse', 'Cabinet', 'Other']) ,class: "form-control devises" %>
    <br>
    <%= f.text_field :devise, class: "other_text", style: "display: none;", id: "other_textbox" %>
  </div>

  <div class="form-group">
    <%= f.label :complain_details %>
    <%= f.text_area :complain, class: "form-control" %>
  </div>

  <div class="actions">
    <%= button_tag "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
</div>
<script type="text/javascript">
  $( "#complain_devise" ).select2({
    theme: "bootstrap"
  });

  $('#complain_devise').change(function() {
    if(this.value == "Other") {
      $('.other_text').val('');
      $('.other_text').show();
    }else{
      $('.other_text').val(this.value);
      $('.other_text').hide();
    }
  });
</script>

app/views/complains/edit.html.erb
<!-- <h1>Editing Complain</h1> -->

<%= render 'form', complain: @complain %>

<%= link_to 'Show', @complain %> |
<%= link_to 'Back', complains_path %>

app/views/complains/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<% if current_user.email.eql?("sagar@thinkbiz.co.in") %>
    <h1>User Complains</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="cntr">Name</th>
          <th class="cntr">User</th>
          <th class="cntr">Devise</th>
          <th class="cntr">Complain</th>
          <th class="cntr" colspan="3">Action</th>
        </tr>
      </thead>

      <tbody>
        <% @complains.each do |complain| %>
          <tr>
            <td class="cntr"><%= complain.name %></td>
            <td class="cntr"><%= complain.user_id %></td>
            <td class="cntr"><%= complain.devise %></td>
            <td class="cntr"><%= complain.complain %></td>
            <td class="cntr"><%= link_to '', complain, class: "btn btn-primary glyphicon glyphicon-eye-open" %></td>
            <td class="cntr"><%= link_to '', edit_complain_path(complain), class: "btn btn-warning glyphicon glyphicon-edit" %></td>
            <td class="cntr"><%= link_to '', complain, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger glyphicon glyphicon-trash" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% else %>

    <h1><%= current_user.username %>'s Complain</h1>
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="cntr">Complain Date</th>
          <th class="cntr">Your id</td>
          <th class="cntr">Devise</th>
          <th class="cntr">Complain</th>
        </tr>
      </thead>
      <tbody>
        <% @not_all.each do |complain| %>
          <% if current_user.id.eql?(current_user.id) %>
            <tr>
              <td class="cntr"><%= complain.created_at %></td>
              <td class="cntr"><%= complain.user_id %></td>
              <td class="cntr"><%= complain.devise %></td>
              <td class="cntr"><%= complain.complain %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
<% end %>

<br>

<%= link_to 'New Complain', new_complain_path %>

app/views/complains/new.html.erb
<!-- <h1>New Complain</h1> -->

<%= render 'form', complain: @complain %>

<%#= link_to 'Back', complains_path %>

app/views/complains/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
<div class="well col-md-4 col-md-offset-4">
  <h1 class="well">Show Complain</h1>
<p>
  <strong>Name:</strong>
  <%= @complain.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @complain.user_id %>
</p>

<p>
  <strong>Devise:</strong>
  <%= @complain.devise %>
</p>

<p>
  <strong>Complain:</strong>
  <%= @complain.complain %>
</p>

<%= link_to 'Edit', edit_complain_path(@complain), class: "btn btn-primary" %>
<%= link_to 'Back', infos_path, class: "btn btn-danger" %>
</div>