config/routes.rb
Rails.application.routes.draw do
  resources :complains
  get 'admin_user/index'
  get 'admin_user/change_pass/:id', to: 'admin_user#change_pass', as: :admin_user_change_pass
  get 'admin_user/new'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "infos#index", as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :infos do
    get 'download_csv', :on => :collection
    #get "import"
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/print_pdf", to: "infos#print_pdf"

  patch '/admin_user/:id/update', to: 'admin_user#update', as: :update_admin_user
  #patch '/user/:id/update', to: 'admin_users#update', as: :update_admin_user
end

app/controllers/admin_user_controller.rb
class AdminUserController < ApplicationController
  def index
    @users = User.all
  end

  def new
  end

  def edit

  end

  def change_pass
    @user =  User.find(params[:id])
  end

  def update
    respond_to do |format|
      @user = User.find(params[:id])
      if @user.update(user_params)
        format.html { redirect_to admin_user_index_path, notice: 'User successfully updated.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to root_path }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_user_helper.rb
module AdminUserHelper
end

app/views/admin_user/change_pass.html.erb
<div class="page-header">
  <h1 class="well well-sm"><%=t '.Password Change' %></h1>
</div>
<%= form_for @user, url: update_admin_user_path(params[:id]), :html => { :class => "form-horizontal company", id: 'user_validation' } do |f| %>

  <div class="form-group">
    <%= f.label :email, :class => 'col-lg-2' %>
    <div class="col-lg-6">
      <div class='col-md-6'>
        <%= f.email_field :email, :class => 'form-control' %>
        <%= f.error_span(:email) %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, :class => 'col-lg-2' %>
    <div class="col-lg-6">
      <div class='col-md-6'>
        <%= f.password_field :password, :class => 'form-control' %>
      </div>
    </div>
    <%=f.error_span(:password) %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, :class => 'col-lg-2' %>
    <div class="col-lg-6">
      <div class='col-md-6'>
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
      </div>
    </div>
    <%=f.error_span(:password_confirmation) %>
  </div>


  <div class="actions">
      <div class="form-group">
        <div class="col-lg-10">
          <%= f.button 'Submit', :class => 'btn btn-primary', data: {disable_with: "<i class='fa fa-spin fa-spinner'></i> Submitting.."} %>
          <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_user_index_path, :class => 'btn btn-default' %>
        </div>
      </div>
  </div>

<% end %>

app/views/admin_user/index.html.erb
<!-- <h1>AdminUser#index</h1>
<p>Find me in app/views/admin_user/index.html.erb</p> -->
<div class="page-header">
  <h1 class="well well-sm"><%=t '.Users' %></h1>
</div>
<table class="table table-hover">
<thead>
  <tr>
    <th>Profile Pics</th>
    <th>Username</th>
    <th>Email</th>
    <th>Admin User</th>
    <th>Change Password</th>
  </tr>
</thead>
<tbody>
  <% @users.order("email").each do |user| %>
    <tr>
      <td>
        <% if user.avatar.present? %>
          <%= image_tag user.avatar.url(:thumb) %>
        <% end %>
      </td>
      <td>
        <%= user.username %>
      </td>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= user.email.eql?("sagar@thinkbiz.co.in") ? "Admin" : "Not Admin" %>
      </td>
      <td>
          <%= link_to "".html_safe, admin_user_change_pass_path(user), :class => 'btn btn-primary glyphicon glyphicon-lock', :style => "left: 35px;", data: {disable_with: "<i class='fa fa-spin fa-spinner'></i>"} %>
      </td>
    </tr>
  <% end %>
</tbody>

</table>

app/views/admin_user/new.html.erb
<h1>AdminUser#new</h1>
<p>Find me in app/views/admin_user/new.html.erb</p>