config/routes.rb
Rails.application.routes.draw do
  resources :complains
  get 'admin_user/index'
  get 'admin_user/change_pass/:id', to: 'admin_user#change_pass', as: :admin_user_change_pass
  get 'admin_user/new'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "infos#index", as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :infos do
    get 'download_csv', :on => :collection
    #get "import"
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/print_pdf", to: "infos#print_pdf"

  patch '/admin_user/:id/update', to: 'admin_user#update', as: :update_admin_user
  #patch '/user/:id/update', to: 'admin_users#update', as: :update_admin_user
end

app/models/info.rb
class Info < ApplicationRecord
  require 'csv'

# To Upload a CSV file...

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      info_hash = row.to_hash
      info = Info.where(id: info_hash[:id])
      if info.count == 1
        info.first.update_attributes(info_hash)
      else
        info.create!(info_hash)
      end
    end
  end

#To download a CSV file...

  def self.to_csv
    CSV.generate do |csv|
      # all column will be fetch...
        #csv << column_names
      # Specific column will be fetch...
        csv << ['Sr No.', 'name', 'monitor', 'motherboard', 'processor', 'ram', 'hdd', 'cabinet', 'keyboard', 'mouse', 'mousepad', 'camera', 'speaker', 'headphone']
      all.each_with_index do |infos, index|
        puts index
        #csv << infos.attributes.values_at(*column_names)
        csv << [index += 1,
          infos.name, infos.monitor, infos.motherboard, infos.processor, infos.ram, infos.hdd, infos.cabinet, infos.keyboard, infos.mouse, infos.mousepad, infos.camera, infos.speaker, infos.headphone ]
      end
    end
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]

  # GET /infos
  # GET /infos.json
  def index
    if params[:search].present?
      #@infos = Info.find(:all, :conditions => ["name LIKE ? ", "%#{params[:search]}%"])
      @infos = Info.where("(name || monitor || motherboard || processor || ram || hdd || cabinet || keyboard || mouse || mousepad || camera || speaker || headphone ) ILIKE ?", "%#{params[:search]}%").order(:id).paginate(:page => params[:page], :per_page => 10)
      #@infos = Info.search(params[:search]).all
    else
      @infos = Info.all.order(:id).paginate(:page => params[:page], :per_page => 10)
    end
    # respond_to do |format|
    #   format.html
    #   format.pdf do
    #     send_data Info.draw(@infos), :filename => "Sytem_configure.pdf", :type => "application/pdf", :disposition => "inline"
    #   end
    # end
  end

  def print_pdf
    @infos = Info.all.order(:id)
		PDFKit.configure do |config|
  			config.default_options = { :page_size => 'Letter', :margin_top => 15, :margin_left => 15,
    			:margin_right => 15,
    			:footer_right => 'Page [page] / [toPage]', :encoding => 'UTF-8', :print_media_type => true }
		end
		html = render_to_string(:action => "print_pdf.html.erb", :layout => false)
    kit = PDFKit.new(html, :orientation => 'Portrait')
    send_data(kit.to_pdf,:disposition => 'attachment', :filename => "SystemConfiguration.pdf", :type => 'application/pdf')

  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  def download_csv
    @infos = Info.order(:id)
    respond_to do |format|
        format.html
        format.csv{ send_data @infos.to_csv, filename: "System Configuration.csv" }
    end
  end

  def import
    Info.import(params[:file])
    redirect_to root_url, notice: "Data imported successfully..."
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:name, :monitor, :motherboard, :processor, :ram, :hdd, :cabinet, :keyboard, :mouse, :mousepad, :camera, :speaker, :headphone, :graphics_card)
    end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_body.html.erb
  <tbody class="">
    <% @infos.each do |info| %>
      <tr>
        <td class="cntr"><%= info.id %></td>
        <td class="cntr"><%= info.name %></td>
        <td class="cntr"><%= info.monitor %></td>
        <td class="cntr"><%= info.motherboard %></td>
        <td class="cntr"><%= info.processor %></td>
        <td class="cntr"><%= info.ram %></td>
        <td class="cntr"><%= info.hdd %></td>
        <td class="cntr"><%= info.cabinet %></td>
        <td class="cntr"><%= info.keyboard %></td>
        <td class="cntr"><%= info.mouse %></td>
        <td class="cntr"><%= info.mousepad %></td>
        <td class="cntr"><%= info.camera %></td>
        <td class="cntr"><%= info.speaker %></td>
        <td class="cntr"><%= info.headphone %></td>
        <td class="cntr"><%= info.graphics_card.present? ? info.graphics_card : "-" %></td>

        <% if current_user.try(:email).eql?("sagar@thinkbiz.co.in")%>
          <td class="cntr"><%= link_to '', info, class: "btn btn-primary glyphicon glyphicon-eye-open" %></td>
          <td class="cntr"><%= link_to '', edit_info_path(info), class: "btn btn-warning glyphicon glyphicon-edit" %></td>
          <td class="cntr"><%= link_to '', info, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger glyphicon glyphicon-trash" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>

app/views/infos/_form.html.erb
<div class="well col-md-4 col-md-offset-4">
<%= form_for(info, html: {class: ""}) do |f| %>
  <% if info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if request.original_url.include? "infos/new" %>
      <h1 class="well">New Information</h1>
    <% elsif request.original_url.include? "infos/#{params[:id]}/edit" %>
      <h1 class="well">Edit Information</h1>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :monitor %>
      <%= f.text_field :monitor, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :motherboard %>
      <%= f.text_field :motherboard, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :processor %>
      <%= f.text_field :processor, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :ram %>
      <%= f.text_field :ram, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :hdd %>
      <%= f.text_field :hdd, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :cabinet %>
      <%= f.text_field :cabinet, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :keyboard %>
      <%= f.text_field :keyboard, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :mouse %>
      <%= f.text_field :mouse, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :mousepad %>
      <%#= f.text_field :mousepad, class: "form-control"  %>
      <%= f.radio_button :mousepad, "Yes" %> Yes
      <%= f.radio_button :mousepad, "No" %> No
    </div>

    <div class="form-group">
      <%= f.label :camera %>
      <%= f.text_field :camera, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :speaker %>
      <%= f.text_field :speaker, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :headphone %>
      <%= f.text_field :headphone, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :graphics_card %>
      <%= f.text_field :graphics_card, class: "form-control"  %>
    </div>

    <div class="actions">
      <!-- <%#= f.submit %> -->
        <%= button_tag "submit", class: "btn btn-primary" %>
        <%= link_to 'Back', infos_path, class: "btn btn-danger" %>
    </div>
<% end %>
</div>

app/views/infos/_head.html.erb
<thead class="">
  <tr class="cntr">
    <th class="cntr">Sr.</th>
    <th class="cntr">Name</th>
    <th class="cntr">Monitor</th>
    <th class="cntr">Motherboard</th>
    <th class="cntr">Processor</th>
    <th class="cntr">Ram</th>
    <th class="cntr">Hdd</th>
    <th class="cntr">Cabinet</th>
    <th class="cntr">Keyboard</th>
    <th class="cntr">Mouse</th>
    <th class="cntr">Mousepad</th>
    <th class="cntr">Camera</th>
    <th class="cntr">Speaker</th>
    <th class="cntr">Headphone</th>
    <th class="cntr">Graphics Card</th>

    <% if current_user.try(:email).eql?("sagar@thinkbiz.co.in")%>
      <th colspan="3" class="cntr">Actions</th>
    <% end %>
  </tr>
</thead>

app/views/infos/edit.html.erb
<%= render 'form', info: @info %>

<%#= link_to 'Show', @info %>
<%#= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
  <div>
    <%= form_tag infos_path, class: "well pull-right", style: "width:350px;", method: "get" do %>
      <%= label_tag :search %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", class: "btn btn-default" %>
    <% end %>
  </div>
<h1 class="">System Configuration</h1>
<table class="table table-hover">
  <%= render :partial => 'head' %>
  <%= render :partial => "body" %>
</table>
<br>
  <% if current_user.email.eql?("sagar@thinkbiz.co.in") %>
    <div class="container">
      <%= form_tag import_infos_path, multipart: true, style: "display: inline-block !important;" do %>
      <%= file_field_tag :file, style: "display: inline-block !important;" %>
      <%= submit_tag "Upload CSV", class: " btn btn-primary" %>
      <% end %>
      <%= link_to 'New Info', new_info_path, class: "btn btn-primary" %>
      <%#= link_to 'Download CSV', download_csv_infos_path(format: 'csv'), class: "btn btn-primary" %>

      <%#= link_to "Download PDF", print_pdf_path(@infos, :format => "pdf"), class: "btn btn-primary", id: "pdf_link" %>
      <%= link_to 'Clear', infos_path, class: "btn btn-danger" %>
    </div>
  <% end %>
  <div class="clearfix"></div>
  <%= will_paginate @infos, renderer: BootstrapPagination::Rails, style: "margin: 10 auto !important;" %>

app/views/infos/new.html.erb
<%= render 'form', info: @info %>

app/views/infos/print_pdf.html.erb
<h1 style="text-align: justify;text-align-last:center;">System Configuration</h1>
<table class="table table-striped">
<thead>
  <tr class="cntr">
    <th class="cntr">Sr.</th>
    <th class="cntr">Name</th>
    <th class="cntr">Monitor</th>
    <th class="cntr">Motherboard</th>
    <th class="cntr">Processor</th>
    <th class="cntr">Ram</th>
    <th class="cntr">Hdd</th>
    <th class="cntr">Cabinet</th>
    <th class="cntr">Keyboard</th>
    <th class="cntr">Mouse</th>
    <th class="cntr">Mousepad</th>
    <th class="cntr">Camera</th>
    <th class="cntr">Speaker</th>
    <th class="cntr">Headphone</th>
  </tr>
</thead>
<tbody>
  <% @infos.each do |info| %>
    <tr>
      <td class="cntr"><%= info.id %></td>
      <td class="cntr"><%= info.name %></td>
      <td class="cntr"><%= info.monitor %></td>
      <td class="cntr"><%= info.motherboard %></td>
      <td class="cntr"><%= info.processor %></td>
      <td class="cntr"><%= info.ram %></td>
      <td class="cntr"><%= info.hdd %></td>
      <td class="cntr"><%= info.cabinet %></td>
      <td class="cntr"><%= info.keyboard %></td>
      <td class="cntr"><%= info.mouse %></td>
      <td class="cntr"><%= info.mousepad %></td>
      <td class="cntr"><%= info.camera %></td>
      <td class="cntr"><%= info.speaker %></td>
      <td class="cntr"><%= info.headphone %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/infos/show.html.erb
<div class="well col-md-4 col-md-offset-4">
  <!-- <p id="notice"><%#= notice %></p> -->
  <div class="well">
    <h2>View Configuration</h2>
  </div>

  <p>
    <strong>Name:</strong>
    <%= @info.name %>
  </p>

  <p>
    <strong>Monitor:</strong>
    <%= @info.monitor %>
  </p>

  <p>
    <strong>Motherboard:</strong>
    <%= @info.motherboard %>
  </p>

  <p>
    <strong>Processor:</strong>
    <%= @info.processor %>
  </p>

  <p>
    <strong>Ram:</strong>
    <%= @info.ram %>
  </p>

  <p>
    <strong>Hdd:</strong>
    <%= @info.hdd %>
  </p>

  <p>
    <strong>Cabinet:</strong>
    <%= @info.cabinet %>
  </p>

  <p>
    <strong>Keyboard:</strong>
    <%= @info.keyboard %>
  </p>

  <p>
    <strong>Mouse:</strong>
    <%= @info.mouse %>
  </p>

  <p>
    <strong>Mousepad:</strong>
    <%= @info.mousepad %>
  </p>

  <p>
    <strong>Camera:</strong>
    <%= @info.camera %>
  </p>

  <p>
    <strong>Speaker:</strong>
    <%= @info.speaker %>
  </p>

  <p>
    <strong>Headphone:</strong>
    <%= @info.headphone %>
  </p>

  <%= link_to 'Edit', edit_info_path(@info), class: "btn btn-warning" %>
  <%= link_to 'Back', infos_path, class: "btn btn-primary" %>
</div>