config/routes.rb
Rails.application.routes.draw do
  resources :complains
  get 'admin_user/index'
  get 'admin_user/change_pass/:id', to: 'admin_user#change_pass', as: :admin_user_change_pass
  get 'admin_user/new'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root "infos#index", as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :infos do
    get 'download_csv', :on => :collection
    #get "import"
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/print_pdf", to: "infos#print_pdf"

  patch '/admin_user/:id/update', to: 'admin_user#update', as: :update_admin_user
  #patch '/user/:id/update', to: 'admin_users#update', as: :update_admin_user
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SystemConfiguration</title>
    <%= csrf_meta_tags %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'icon_computer.png', :rel => 'shortcut icon' %>
  </head>

  <body>
    <%= nav_bar fixed: :top, brand: "<span class='text-default'>System Configuration".upcase.html_safe, responsive: true do %>
      <%= menu_group do %>
        <%= menu_divider %>
      <% end %>
        <%= menu_group pull: :right do %>
          <% if user_signed_in? %>
            <%= drop_down "<i class='glyphicon glyphicon-home' aria-hidden='true'></i> Menu".html_safe do %>
              <div class="row">
                  <div class="col-lg-3">
                    <strong class="text-default">Operations</strong><hr>
                    <% if current_user.email.eql?("sagar@thinkbiz.co.in") %>
                      <%= menu_item "New Information", new_info_path %>
                    <% end %>
                    <%= menu_item "Request Complain", new_complain_path %>
                  </div>
                <div class="col-lg-3">
                <strong class="text-default">Exports</strong><hr>
                  <%= menu_item "Download CSV", download_csv_infos_path(format: 'csv') %>
                  <%= menu_item "Download PDF", print_pdf_path(@infos, :format => "pdf") %>
                </div>
                <div class="col-lg-3">
                  <strong class="text-default">List/Views</strong><hr>
                    <%= menu_item 'Edit User Profile',edit_user_registration_path %>
                    <%= menu_item 'Delete Account', user_registration_path, data: {:confirm => 'Are you sure you want to destroy your account?'}, :method => :delete %>
                  <% if current_user.email.eql?("sagar@thinkbiz.co.in") %>
                    <%= menu_item "Views Users", admin_user_index_path %>
                  <% end %>
                </div>
                <!-- Admin can see all complains -->
                <% if current_user.email.eql?("sagar@thinkbiz.co.in") %>
                  <div class="col-lg-3">
                  <strong class="text-default">Complains</strong><hr>
                    <%= menu_item "Show Complain", complains_path %>
                  </div>
                <% else %>
                <!-- For other users complain -->
                <div class="col-lg-3">
                  <strong class="text-default">Complains</strong><hr>
                    <%= menu_item "Complain Logs", complains_path %>
                </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <% if current_user %>
            <li class="round-image-50">
              <% if current_user.avatar.present? %>
                <%= image_tag(current_user.avatar.url(:thumb)) %>
              <% end %>
            </li>
            <%= menu_item "<i class='glyphicon glyphicon-user' aria-hidden='true'></i> Welcome, #{current_user.username}".html_safe %>
            <%= menu_item "<i class='glyphicon glyphicon-log-out' aria-hidden='true'></i> Log Out".html_safe, "javascript:void(0)", data:{ toggle: "modal", target: "#LogoutModal" }  %>
          <% else %>
            <%= menu_item '<i class="glyphicon glyphicon-log-in" aria-hidden="true"></i>&nbsp;Login'.html_safe, new_user_session_path %>
          <% end %>
        <% end %>
    <% end %>
    <br><br>
    <!-- toastr messages display...  -->
    <% unless flash.empty? %>
	  <script type="text/javascript">
	      <% flash.each do |f| %>
	      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
	     	 toastr['<%= type %>']('<%= f[1] %>');
	      <% end %>
	  </script>
	 <% end %>
    <!-- <p class="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>-->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row col-md-12">
        <div class="col-lg-12">
             <%#= bootstrap_flash %>
            <%= yield %>
        </div>
      </div>
    </div>

    <!-- Modal open when user click on Logout Button...  -->
    <div id="LogoutModal" class="modal fade" role="dialog" style="text-align:center;">
      <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content" style="width:390px;">
          <!-- <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Modal Header</h4>
          </div> -->
          <div class="modal-body">
            <h3>Are you sure want to Logout ?</h3>
          </div>
          <div class="modal-footer">
            <%= link_to "Yes", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
            <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
          </div>
        </div>
      </div>
    </div>

    <footer>
      <p>&copy; Company 2016 <span class="pull-right"> powered By - Vebuin Inc. </span></p>
    </footer>
  </body>
</html>